// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_netbox

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func NetboxProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type NetboxModel struct {
}
